name: Linting and Testing
on:
  push:
    branches: [main, csipaus.org/ns/v1.3-beta/storage]
  pull_request:
    branches: [main, csipaus.org/ns/v1.3-beta/storage]
  workflow_dispatch:

jobs:
  # This will run bandit and produce a security report if there are any failures
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install bandit[toml]

      - name: Security check - Bandit
        run: bandit -r -c pyproject.toml .

  # This will run the latest flake8 with python 3.12 and report on any errors
  flake8_py312:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Lint with flake8
        if: always()
        run: |
          pip install flake8
          flake8 . --count --statistics

  # This will run the latest black to see if there are any code formatting errors
  black_formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable

  # This will run the latest mypy with python3.12 to see if there are any type errors
  mypy_py312:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install .[dev]

      - name: Run mypy
        run: mypy .

  # This will run pytest against the specified version
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyver: ["3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.pyver }}

      - name: Install Dependencies
        run: |
          pip install .[test]

      - name: Run Pytest
        run: pytest

      
